config/routes.rb
Rails.application.routes.draw do

 

  use_doorkeeper  do
    skip_controllers :authorizations, :applications, :authorized_applications
  end

   #doorkeeper
   namespace :api do
    
      resources :posts
    
  end

  # API
  namespace :api do
    namespace :v1 do
      resources :communities
    end
  end



  namespace :api do
    namespace :v1 do
      resources :likes do
        collection do
          get :comment_likes
          get :post_likes
        end
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :comments
    end
  end

  namespace :api do
    namespace :v1 do
      resources :accounts
    end
  end

  namespace :api do
    namespace :v1 do
      resources :posts do
        member do
          get :post_title
          get :post_likes
          get :post_comments
        end
      end
  end
end
  

 #main routes

  resources :memberships
  resources :groups  

  resources :communities

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  resources :accounts
  # get '/accounts', to: 'accounts#index'

 
  devise_for :users
  
  resources :likes, only: [:create, :destroy]
  
  root "posts#index"

  get 'home/about'

  resources :posts do
    resources :comments
  end
 
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, length:{minimum:5,maximum:25}

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  has_many :likes, as: :likeable,dependent: :destroy
  belongs_to :user

end

app/models/community.rb
class Community < ApplicationRecord
    has_many :groups,dependent: :destroy
    has_many :users, through: :groups

    validates :name, presence: true, length:{minimum:5,maximum:100}
end

app/models/group.rb
class Group < ApplicationRecord


  belongs_to :community
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  
  validates :name, presence: true, length:{minimum:3,maximum:100}

end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: {scope: [:likeable_id, :likeable_type] }
  belongs_to :user
  belongs_to :likeable, polymorphic: true

  scope :comment, ->{ where(:likeable_type => 'Comment') }
  scope :post, -> { where(:likeable_type => 'Post') }
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :group

 

end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments,dependent: :destroy
    
    validates :title, presence: true, length:{minimum:3,maximum:100}
    validates :description, presence: true,length:{minimum:3,maximum:1000}
    validates :keyword, presence: true,length:{minimum:3,maximum:100}

    has_many_attached :images
    has_many :likes, as: :likeable
    belongs_to :user


    scope :Hello, -> {
      where(:title => "Hello")
    }

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  

  validates :email, format: URI::MailTo::EMAIL_REGEXP
  
  


 #group-community-associations
  has_many :memberships
  has_many :groups, through: :memberships
  has_many :communities, through: :groups
  

  has_many :likes
  has_many :posts
  has_one :account
  has_many :comments

  
   def self.authenticate(email, password)
    user = User.find_for_authentication(email: email)
    user&.valid_password?(password) ? user : nil
  end


after_create :create_account
  
private
    def create_account
      username = self.email.split('@').first.upcase
      Account.create(name:username, user_id: self.id)
    end
    
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

def index
 @groups=Group.all
end

def new
 @group=Group.new
end

def show
    @group = Group.find(params[:id])
    @users= @group.users
   
end



def create
    @group=Group.new(group_params) 
    if @group.save
        redirect_to @group
    else
        render 'new'
    end
end

def destroy
    @group = Group.find(params[:id])
    @group.destroy

    redirect_to groups_path, notice: "Group was successfully deleted."
  end

private
    def group_params
        params.require(:group).permit(:name,:community_id)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @like = current_user.likes.new(like_params)
     if !@like.save
        flash[:notice] = @like.errors.full_messages.to_sentence
     end
     redirect_back(fallback_location: posts_url)
    end

    def destroy
        @like = current_user.likes.find(params[:id])
        likeable = @like.likeable
        @like.destroy
        redirect_back(fallback_location: posts_url)
    end

    private
     def like_params
        params.require(:like).permit(:likeable_id, :likeable_type)
     end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/hash_tags_helper.rb
module HashTagsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/membership_helper.rb
module MembershipHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/groups/index.html.erb
<div class="container">
<h2> List of Groups </h2>

  <ul class="list-group">
  <% @groups.each do |f|   %>
      <li class="list-group-item"><%= link_to f.name, group_path([f.id]),class: "nav-link"%></li>
    <% end %>
  </ul>

  <div class="mt-3">
  <table><tbody><tr>
  <%= link_to "back", posts_path,class:"button" %> &nbsp; 
  <%= link_to "Create New Group", new_group_path, class: "button1" %> &nbsp; 
  <%= link_to "Add User In Group", new_membership_path, class: "button1" %> </table></tbody></tr>
    </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">Create New Group</div>
        <div class="card-body">
          <%= form_with model: @group, url: groups_path do |form| %>
            <div class="form-group">
              <%= form.label :name %>
              <%= form.text_field :name, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= form.label :community_id, "Select a community:" %>
              <%= form.select :community_id, options_from_collection_for_select(Community.all, :id, :name), {}, { class: 'form-control' } %>
            </div>
            <div class="form-group">
            <%= link_to 'Back', groups_path, class: "button" %>
              <%= form.submit class: "button" %>
             
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container">
<h1><%= @group.name %></h1>

  <ul class="list-group">
  <% @users.each do |f| %>
      <li class="list-group-item"><%= f.account.name %></li>
    <% end %>
  </ul>

  <div class="mt-3">
  <table><tbody><tr>
  <%= link_to "back", groups_path,class:"button" %> &nbsp; 
  <%= button_to 'Delete Group', @group, method: :delete, data: { confirm: 'Are you sure?' } ,class:"button"%>
    </table></tbody></tr>
    </div>
</div>