config/routes.rb
Rails.application.routes.draw do

 

  use_doorkeeper  do
    skip_controllers :authorizations, :applications, :authorized_applications
  end

   #doorkeeper
   namespace :api do
    
      resources :posts
    
  end

  # API
  namespace :api do
    namespace :v1 do
      resources :communities
    end
  end



  namespace :api do
    namespace :v1 do
      resources :likes do
        collection do
          get :comment_likes
          get :post_likes
        end
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :comments
    end
  end

  namespace :api do
    namespace :v1 do
      resources :accounts
    end
  end

  namespace :api do
    namespace :v1 do
      resources :posts do
        member do
          get :post_title
          get :post_likes
          get :post_comments
        end
      end
  end
end
  

 #main routes

  resources :memberships
  resources :groups  

  resources :communities

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  resources :accounts
  # get '/accounts', to: 'accounts#index'

 
  devise_for :users
  
  resources :likes, only: [:create, :destroy]
  
  root "posts#index"

  get 'home/about'

  resources :posts do
    resources :comments
  end
 
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, length:{minimum:5,maximum:25}

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  has_many :likes, as: :likeable,dependent: :destroy
  belongs_to :user

end

app/models/community.rb
class Community < ApplicationRecord
    has_many :groups,dependent: :destroy
    has_many :users, through: :groups

    validates :name, presence: true, length:{minimum:5,maximum:100}
end

app/models/group.rb
class Group < ApplicationRecord


  belongs_to :community
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  
  validates :name, presence: true, length:{minimum:3,maximum:100}

end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: {scope: [:likeable_id, :likeable_type] }
  belongs_to :user
  belongs_to :likeable, polymorphic: true

  scope :comment, ->{ where(:likeable_type => 'Comment') }
  scope :post, -> { where(:likeable_type => 'Post') }
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :group

 

end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments,dependent: :destroy
    
    validates :title, presence: true, length:{minimum:3,maximum:100}
    validates :description, presence: true,length:{minimum:3,maximum:1000}
    validates :keyword, presence: true,length:{minimum:3,maximum:100}

    has_many_attached :images
    has_many :likes, as: :likeable
    belongs_to :user


    scope :Hello, -> {
      where(:title => "Hello")
    }

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  

  validates :email, format: URI::MailTo::EMAIL_REGEXP
  
  


 #group-community-associations
  has_many :memberships
  has_many :groups, through: :memberships
  has_many :communities, through: :groups
  

  has_many :likes
  has_many :posts
  has_one :account
  has_many :comments

  
   def self.authenticate(email, password)
    user = User.find_for_authentication(email: email)
    user&.valid_password?(password) ? user : nil
  end


after_create :create_account
  
private
    def create_account
      username = self.email.split('@').first.upcase
      Account.create(name:username, user_id: self.id)
    end
    
  
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/hash_tags_helper.rb
module HashTagsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/membership_helper.rb
module MembershipHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small blue pt-4" style ="margin-top:auto;
margin-left: 0%;background-color:red;height:70px;">
  <div class="footer-copyright text-center py-2">© 2023 Copyright:
    <a href="/"> MyInsta.com</a>
  </div>
 

</footer>

app/views/layouts/_navbar.html.erb
<%= stylesheet_link_tag("layout")%>
<nav class="navbar navbar-expand-lg navbar-light bg-danger">
<%= link_to "Home", root_path, class:"navbar-brand hover-effect" %>


    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          
        </li>
        <li class="nav-item">
        <%= link_to "Upload Post" , new_post_path,class:"nav-link hover-effect header-element" %>
        </li>

        <li class="nav-item hover-effect">
        <%= link_to "About Us",home_about_path,class:"nav-link hover-effect header-element"%>
        </li>

        <li class="nav-item hover-effect">
        <%= link_to "Community",communities_path,class:"nav-link hover-effect header-element"%>
        </li>

        <li class="nav-item hover-effect">
        <%= link_to "Group",groups_path,class:"nav-link hover-effect header-element"%>
        </li>

        
      </ul>

      





      
    <p class="navbar-text float-right">
        <%if user_signed_in? %>

        <div class="dropdown">
      <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown">
        <%= current_user.email %>
      </button>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="#"><%= link_to "My Account" , accounts_path,class: "nav-link"%></a>
        <a class="dropdown-item" href="#"> <%= link_to "Change Password",edit_user_registration_path,class:"nav-link"%></a>
        <a class="dropdown-item" href="#"> <%= button_to "Sign Out", destroy_user_session_path,method: :delete,class:"btn btn-info nav-link"%></a>
      </div>
    </div>


        <li class="nav-item"style="list-style-type:none">
           <strong></strong>.
          </li>
        <li class="nav-item"style="list-style-type:none;">
       
      </li>
        <li class="nav-item"style="list-style-type:none;">
       
      </li>

      <%else %>

      <li class="nav-item"style="list-style-type:none;">
      <%= link_to "Sign Up",new_user_registration_path,class:"nav-link"%>
      </li>

        <li class="nav-item"style="list-style-type:none;">
        <%= link_to "Sign In", new_user_session_path,class:"nav-link"%>
        </li>
      <%end%>
    </p>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyInsta</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" 
    href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
    crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <style>
    body{
      background-color:#ffffff;
    }
    </style>

  <body style="min-height:100vh;display:flex;flex-direction:column;">
    <%= render "layouts/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>  


    <%= yield %>

    <%= render "layouts/footer" %>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</html>