config/routes.rb
Rails.application.routes.draw do

 

  use_doorkeeper  do
    skip_controllers :authorizations, :applications, :authorized_applications
  end

   #doorkeeper
   namespace :api do
    
      resources :posts
    
  end

  # API
  namespace :api do
    namespace :v1 do
      resources :communities
    end
  end



  namespace :api do
    namespace :v1 do
      resources :likes do
        collection do
          get :comment_likes
          get :post_likes
        end
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :comments
    end
  end

  namespace :api do
    namespace :v1 do
      resources :accounts
    end
  end

  namespace :api do
    namespace :v1 do
      resources :posts do
        member do
          get :post_title
          get :post_likes
          get :post_comments
        end
      end
  end
end
  

 #main routes

  resources :memberships
  resources :groups  

  resources :communities

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  resources :accounts
  # get '/accounts', to: 'accounts#index'

 
  devise_for :users
  
  resources :likes, only: [:create, :destroy]
  
  root "posts#index"

  get 'home/about'

  resources :posts do
    resources :comments
  end
 
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, length:{minimum:5,maximum:25}

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  has_many :likes, as: :likeable,dependent: :destroy
  belongs_to :user

end

app/models/community.rb
class Community < ApplicationRecord
    has_many :groups,dependent: :destroy
    has_many :users, through: :groups

    validates :name, presence: true, length:{minimum:5,maximum:100}
end

app/models/group.rb
class Group < ApplicationRecord


  belongs_to :community
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  
  validates :name, presence: true, length:{minimum:3,maximum:100}

end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: {scope: [:likeable_id, :likeable_type] }
  belongs_to :user
  belongs_to :likeable, polymorphic: true

  scope :comment, ->{ where(:likeable_type => 'Comment') }
  scope :post, -> { where(:likeable_type => 'Post') }
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :group

 

end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments,dependent: :destroy
    
    validates :title, presence: true, length:{minimum:3,maximum:100}
    validates :description, presence: true,length:{minimum:3,maximum:1000}
    validates :keyword, presence: true,length:{minimum:3,maximum:100}

    has_many_attached :images
    has_many :likes, as: :likeable
    belongs_to :user


    scope :Hello, -> {
      where(:title => "Hello")
    }

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  

  validates :email, format: URI::MailTo::EMAIL_REGEXP
  
  


 #group-community-associations
  has_many :memberships
  has_many :groups, through: :memberships
  has_many :communities, through: :groups
  

  has_many :likes
  has_many :posts
  has_one :account
  has_many :comments

  
   def self.authenticate(email, password)
    user = User.find_for_authentication(email: email)
    user&.valid_password?(password) ? user : nil
  end


after_create :create_account
  
private
    def create_account
      username = self.email.split('@').first.upcase
      Account.create(name:username, user_id: self.id)
    end
    
  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!
  def index
    @accounts=Account.all
    if current_user.account.present?
      @account=current_user.account
    else
      @account=nil
    end
  end


  def new
    @account=Account.new
  end

  def create
    @account=Account.new(account_params)    
  
    if @account.save
        redirect_to accounts_path ,notice: 'account has been created'
    else
        render :new
    end
  end
  
  def edit
    @account=Account.find(params[:id])
  end
  
  def update
    @account= Account.find(params[:id])
    @account.update(account_params)
    redirect_to accounts_path
  end
  
  
  
  private
  def account_params
    params.require(:account).permit(:name,:address,:phone,:user_id)
  end
end

app/controllers/api/v1/accounts_controller.rb
class Api::V1::AccountsController < ApplicationController
    skip_before_action :authenticate_user! 
    skip_before_action :verify_authenticity_token

    def index
        accounts=Account.all
        render json: accounts
    end

    
  def new
    account=Account.new
  end

  def create
    account=Account.new(account_params)    
  
    if account.save
        render json: account, status: :created
    else
        render json: { error: account.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def show
    account=Account.where(id: params[:id])
    if account.present?
        render json: account
    else 
       render json: { error: "Account not exist "}, status:404
    end
  end

  def destroy
    account=Account.find_by(id:params[:id])
    if account
        account.destroy
        render json: { message: "Account has been Deleted"},status: :ok
    end
  end

  
  def edit
    account=Account.find(params[:id])
  end
  
  def update
    account= Account.where(id: params[:id])
    if account.present?
     account.update(account_params)
     render json: account, status: :ok
    else
        render json: { error: "Record not found" },status:404 
    end
  end
  
  
  
  private
  def account_params
    params.require(:account).permit(:name,:address,:phone,:user_id)
  end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @like = current_user.likes.new(like_params)
     if !@like.save
        flash[:notice] = @like.errors.full_messages.to_sentence
     end
     redirect_back(fallback_location: posts_url)
    end

    def destroy
        @like = current_user.likes.find(params[:id])
        likeable = @like.likeable
        @like.destroy
        redirect_back(fallback_location: posts_url)
    end

    private
     def like_params
        params.require(:like).permit(:likeable_id, :likeable_type)
     end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/hash_tags_helper.rb
module HashTagsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/membership_helper.rb
module MembershipHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/accounts/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">Update Your Account</div>
        <div class="card-body">
          <%= form_with model:@account do |form| %>
            <div class="form-group">
              <%= form.label :name %>
              <%= form.text_field :name, class:'form-control'  %>
            </div>
            <div class="form-group">
              <%= form.label :address %>
              <%= form.text_field :address , class:'form-control' %>
            </div>
            <div class="form-group">
              <%= form.label :phone %>
              <%= form.text_field :phone , class:'form-control' %>
            </div>
            <div class="field">
              <%= form.text_field :user_id, type: "hidden", value: current_user.id %>
            </div>
            <div class="form-group">
              <%= link_to 'Back', accounts_path ,  class:"button" %>
              <%= form.submit 'Update Account' , class:'button' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accounts/index.html.erb
<%= stylesheet_link_tag("account")%>
<div class="container mt-12">

        <div class="col-md-20">
            
            <div class="card p-3 py-4">
                
               
                
                <div class="text-center mt-3">
                    <span class="bg-secondary p-1 px-4 rounded text-white">My Account</span>
                    <% if @account.present? %>
                    <h5 class="mt-2 mb-0"><%= current_user.account.name %></h5>
                    <h5 class="mt-2 mb-0"><%= current_user.account.address %></h5>
                    <h5 class="mt-2 mb-0"><%= current_user.account.phone %></h5>
                    
                    <br><br><br>
                    
                    <div class="buttons">
                        
                        <button class="btn btn-outline-primary px-4"><%= link_to 'Back', posts_path  %> </button>
                        <button class="btn btn-outline-primary px-4"><%= link_to 'Update Account', edit_account_path(@account.id) %></button>
                    </div>

                  
                        <% else %>
                        <br> <br> <br> <br>
                        <button class="btn btn-outline-primary px-4"> <%= link_to 'Back', posts_path  %>   </button>
                        <button class="btn btn-outline-primary px-4">  <%= link_to 'New Account', new_account_path  %>
                        </button>
                          
                       
                        <% end %>
                  
                    
                </div>
                
               
                
                
            </div>
            
        </div>



    
</div>

app/views/accounts/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">Create Your Account</div>
        <div class="card-body">
          <%= form_with model:@account do |form| %>
            <div class="form-group">
              <%= form.label :name %>
              <%= form.text_field :name, class:'form-control'  %>
            </div>
            <div class="form-group">
              <%= form.label :address %>
              <%= form.text_field :address , class:'form-control' %>
            </div>
            <div class="form-group">
              <%= form.label :phone %>
              <%= form.text_field :phone , class:'form-control' %>
            </div>
            <div class="field">
              <%= form.text_field :user_id, type: "hidden", value: current_user.id %>
            </div>
            <div class="form-group">
              <%= link_to 'Back', accounts_path ,  class:"button" %>
              <%= form.submit 'Update Account' , class:'button' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>